config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  get 'flights/new'
  get 'flights/index'

  resources :flights
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :flights 
    has_many :start_airports, class_name: "Flight", foreign_key: "start_airport_id"
    has_many :end_airports, class_name: "Flight", foreign_key: "end_airport_id"
    has_many :departing_flights, through: :start_airports
    has_many :arriving_flights, through: :end_airports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :start_airport, class_name: "Airport", foreign_key: "start_airport_id"
  belongs_to :end_airport, class_name: "Airport", foreign_key: "end_airport_id"


  scope :start_search_results, -> (start_airport) {where start_airport: start_airport}
  scope :end_search_results, -> (end_airport) {where end_airport: end_airport}
  scope :date_search_results, -> (date) {where date: date}
  
  

# scope :start_airport_id, lambda { |start_airport_id|
#   where( "start_airport_id = ?", start_airport_id ) if start_airport_id != ""
# }

# scope :end_airport_id, lambda { |end_airport_id|
#   where( "end_airport_id = ?", end_airport_id ) if end_airport_id != ""
# }

# scope :date, lambda { |date|
#   where( "date = ?", date ) if date != ""
# }

end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   

      
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    passenger_number = params[:passenger_number].to_i
    @booking = Booking.new(flight_id: params[:flight_id])
    
  end


      def create
        @booking = Booking.create!(booking_params)
        redirect_to @booking
      end
    
      def show
        @booking = Booking.find(params[:id])
        @flight = @booking.flight_id
      end
    
      private
        def booking_params
           params.require(:booking).permit(:flight_id, :passengers_attributes =>
             [:id, :name, :email])
        end
        
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
 

  def index

    @flight_start_options = Flight.all.map {|f| [f.start_airport.name, f.start_airport.id] }
    @flight_end_options = Flight.all.map {|f| [f.end_airport.name, f.end_airport.id] }
    @flight_date_options = Flight.all.map {|f| [f.date] }

    @booking = Booking.new
    @passenger_number = params[:passenger_number]

    if params[:start_airport] and params[:end_airport]
      @flights = 
      Flight.start_search_results(params[:start_airport]).end_search_results(params[:end_airport]).date_search_results(params[:date])
    else 
      flash[:danger] = "No flights found"
      @flights = Flight.all 
    end
  end   
    
    # @flights = @flights.start_airport(params[:start_airport]) if params[:start_airport].present?
    # @flights = @flights.end_airport(params[:end_airport]) if params[:end_airport].present?
    # @flights = @flights.date(params[:date]) if params[:date].present?
    # @flights = Flight.where(nil)
    # flight_params(params).each do |key, value|
    #   @flights = @flights.public_send(key, value) if value.present?
    # end
  


  private

  def flight_params
    params.require(:flight).permit(:start_airport, :end_airport, :date)
  end


  
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/new.html.erb
<%= form_for @booking, url: bookings_path do |booking| %>
  <%= booking.hidden_field :flight_id, value: @booking.flight_id %>
  <% params[:passengers].to_i.times do %>
<%= booking.fields_for :passengers, @booking.passengers.build do |p| %>
<%= p.text_field :name %>
<%= p.text_field :email %>
<br>
<% end %>
<% end %>
<%= booking.submit %>
<% end %>

app/views/bookings/show.html.erb
<h4>Booking Number: <%= @booking.id %></h4>
<h3>Flight Number: <%= @flight %></h3>
<ul>
  <%= render @booking.passengers %>
</ul>

app/views/flights/_flight.html.erb
 <%= radio_button_tag :flight_id, flight.id  %>
 <%= flight.start_airport.name %>
 <%= flight.end_airport.name %>
 <%= flight.date %>
 <%= params[:number_of_passengers] %>
 

app/views/flights/index.html.erb
<h1>Search for a flight</h1>


<%= form_for flights_path, :method => :get do %>
<%= select_tag( :start_airport, options_for_select(@flight_start_options) )%>
<%= select_tag( :end_airport, options_for_select(@flight_end_options) )%>
<%= select_tag( :date, options_for_select(@flight_date_options) )%>

<%= fields_for @passengers do |p| %>
    <%= p.label :passengers %>
    <%= p.select(:passenger_number, (1..4)) %>
<% end %>

<%= submit_tag "Submit" %>
<% end %>

<%= form_for '', url: new_booking_path, method: :get do |f| %>
    <%= hidden_field_tag(:passengers, params[:passenger_number]) %>
    <%= render @flights %>
    <%= f.submit %>
<% end %>

 
<%= params.inspect %>

app/views/flights/new.html.erb
<h1>Flights#new</h1>
<p>Find me in app/views/flights/new.html.erb</p>


<% @flights.each do |flight| %>
<ul>
    <li class="list-group">
    <h3>
        <%= flight.start_airport.name %> to <%= flight.end_airport.name %> 
    </h3>
    <p>Date: <%= flight.date %></p>
    <p>Flight time in hours: <%= flight.flight_duration %></p>
    </li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightsFirstTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    	<%= yield %>
    </div>
  </body>
  <div class="navbar fixed-bottom">
    <%= debug(params) if Rails.env.development? %>
  </div>
</html>

app/views/passengers/_passenger.html.erb
<li>
<%= passenger.name %>
<%= passenger.email %>
</li>